services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FOLDER_PROJECT_NAME}_app_image
    container_name: ${FOLDER_PROJECT_NAME}_app
    restart: unless-stopped
    ports:
      - "9000"
    working_dir: /usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    volumes:
      - .:/usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    command: >
      sh -c "
        echo '🚀 Performing FULL cleanup...' &&
        rm -rf vendor composer.lock node_modules bun.lock public/build &&
        echo '🔐 Preparing environment...' &&
        git config --global --add safe.directory '*' &&
        chown -R vcst:vcst . || true &&
        mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache &&
        chown -R vcst:www-data storage bootstrap/cache database || true &&
        chmod -R 775 storage bootstrap/cache database || true &&
        echo '📦 Installing PHP dependencies...' &&
        composer install --no-interaction --optimize-autoloader &&
        if [ -f package.json ]; then
            echo '🍞 Installing JS dependencies...' &&
            bun install &&
            echo '⚡ Building assets...' &&
            bun run build;
        fi &&
        echo '🛠️ Optimizing Laravel...' &&
        php artisan config:clear || true &&
        php artisan route:clear || true &&
        php artisan view:clear || true &&
        php artisan cache:clear || true &&
        php artisan storage:link --force || true &&
        php artisan optimize:clear || true &&
        php artisan filament:optimize-clear || true &&
        php artisan filament:assets || true &&
        php artisan optimize || true &&
        php artisan filament:optimize || true &&
        if [ "$APP_ENV" = "production" ] || [ "$APP_ENV" = "prod" ]; then
            echo '🚀 Production mode detected: Disabling OPcache validate_timestamps for max performance...' &&
            sed -i 's/opcache.validate_timestamps=[0-9]/opcache.validate_timestamps=0/g' /usr/local/etc/php/conf.d/docker-php.ini;
        else
            echo '🛠️ Development mode detected: OPcache validate_timestamps keeping enabled...';
        fi &&
        echo '✅ Ready to go!' &&
        php-fpm -F
      "
    env_file:
      - .env
    environment:
      COMPOSER_PROCESS_TIMEOUT: 2000
    networks:
      - itc-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FOLDER_PROJECT_NAME}_app_image
    container_name: ${FOLDER_PROJECT_NAME}_worker
    restart: unless-stopped
    working_dir: /usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    volumes:
      - .:/usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    depends_on:
      - app
    command: sh -c "until [ -f vendor/autoload.php ]; do echo 'Waiting for composer install...'; sleep 5; done && echo 'Composer dependencies found. Starting worker...' && php artisan queue:work --verbose --tries=3 --timeout=90"
    env_file:
      - .env
    networks:
      - itc-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FOLDER_PROJECT_NAME}_app_image
    container_name: ${FOLDER_PROJECT_NAME}_scheduler
    restart: unless-stopped
    working_dir: /usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    volumes:
      - .:/usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    depends_on:
      - app
    command: sh -c "until [ -f vendor/autoload.php ]; do echo 'Waiting for composer install...'; sleep 5; done && echo 'Composer dependencies found. Starting scheduler...' && while [ true ]; do php artisan schedule:run --no-interaction & sleep 60; done"
    env_file:
      - .env
    environment:
      TZ: Asia/Bangkok
    networks:
      - itc-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  serve:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FOLDER_PROJECT_NAME}_app_image
    container_name: ${FOLDER_PROJECT_NAME}_serve
    restart: unless-stopped
    working_dir: /usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    volumes:
      - .:/usr/share/nginx/html/${FOLDER_PROJECT_NAME}
    depends_on:
      - app
    ports:
      - "${APP_SERVE_PORT}:8000"
    command: sh -c "until [ -f vendor/autoload.php ]; do echo 'Waiting for composer install...'; sleep 5; done && php artisan serve --host=0.0.0.0 --port=8000"
    env_file:
      - .env
    networks:
      - itc-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  itc-network:
    external: true
    name: itc-network